### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by arman29kz** [ThingEngineering/swgoh-status#1]
Hello,

Nice farming calculator (if I can name it like this)

Are you accepting new features? If yes, can you please review these ones:
1. Add **Power** column with the same logic as **Stars, Gear, Relic** column. I mean to write where minimum **Power** required for comfortable event passing;
2. Add **Zeta** column with the same logic as **Stars, Gear, Relic** column. I mean to show how many zetas are required to go. As some heroes are useless and putting zeta is just waste of resources;
3. Additional pages for each Legends/Events where guild members will be shown with current progress of legend/event

Thanks in advance

**Comment by madcowfred** [comment]
Hi!

1. Definitely want to add Power somehow for the events that are Power-gated, but haven't worked out how it will look yet. Adding a new column makes everything wider which is a bit annoying.
2. Zetas aren't really a _requirement_, so I'm not sure about this one.
3. Would like to do this, but the swgoh.gg Guild API returns a LOT of data (13.8MB for my guild) and load times might be interesting.

**Comment by arman29kz** [comment]
Hello!

1. Okey, thanks. Waiting. Just reduce column and put 2 column in the row;
2. I mean to check forums and recommendations what zetas to use and what zeta are useless. And put * in this column and put note under table that is recommend by community;
3. Have you tried plain text without pictures? Only raw CSS and html

**Comment by johnhiggs** [comment]
@madcowfred agreed the main guild api request returns a crapload of json. love what you have done here, i'd love to be able to throw in the guild id and see even a dumbed down version of everything you and ultimately hook it up in a discord bot. awesome job
