### ISSUE TITLE
API - KABOOM! Something has gone horribly wrong, try reloading the page?

### ISSUE THREAD

**Issue by DennisBecker** [ThingEngineering/swgoh-status#33]
The application does not load the data from the API.

HTTP requests like https://cors-anywhere.freddie.wtf/http://api.swgoh.gg/characters/ result in HTTP response 502 Bad Gateway.

**Comment by madcowfred** [comment]
Oh, that helps a lot actually. I rebooted that machine and once again forgot to start the CORS proxy. It should work now?

**Comment by DennisBecker** [comment]
Yes, it works now. Thanks!
