### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by DennisBecker** [ThingEngineering/swgoh-status#42]
I get the following notificcation in Chrome:

```
This site can’t be reached
swgoh.freddie.wtf’s server IP address could not be found.
```

Is the domain not registered anymore? Any workaround? Should I self host this page?

**Comment by tedbrock** [comment]
Is there any way I can view this on computer?  I am not at all a programmer, but I loved this app.  Help?

**Comment by DennisBecker** [comment]
Check out https://thedonproject.com/swgoh/index.cgi - same functionality + Assault Battles
